#! /usr/bin/env python

import rospy
from turtpkg.turtle import Turtle
from turtlesim.msg import Pose

rospy.init_node('cse_move')
rospy.wait_for_message('/turtle1/pose/', Pose)
cseTurtle = Turtle('turtle1')
cseTurtle.prepareForMovement()
#Start Position
cseTurtle.rotate(135)
cseTurtle.move(3)
Turtle.clear()
#C
cseTurtle.rotate(45)
cseTurtle.move(2)
cseTurtle.rotate(90)
cseTurtle.move(2)
cseTurtle.rotate(90)
cseTurtle.move(5)
#S
cseTurtle.rotate(90)
cseTurtle.move(1)
cseTurtle.rotate(90)
cseTurtle.move(1)
cseTurtle.move(1)
cseTurtle.rotate(-90)
cseTurtle.move(1)
cseTurtle.rotate(-90)
cseTurtle.move(5)
#E
cseTurtle.move(-2)
cseTurtle.rotate(-90)
cseTurtle.move(1)
cseTurtle.rotate(90)
cseTurtle.move(1.5)
cseTurtle.move(-1.5)
cseTurtle.rotate(-90)
cseTurtle.move(1)
cseTurtle.rotate(90)
cseTurtle.move(2)
rospy.spin()